<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240801131422 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, login VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE documents ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE documents ALTER name SET NOT NULL');
        $this->addSql('ALTER TABLE documents ALTER name TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE documents ALTER author SET NOT NULL');
        $this->addSql('ALTER TABLE documents ALTER author TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE documents ALTER date SET NOT NULL');
        $this->addSql('ALTER TABLE documents ALTER date TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE documents ALTER state SET NOT NULL');
        $this->addSql('ALTER TABLE documents ALTER state TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE documents ALTER text SET NOT NULL');
        $this->addSql('ALTER TABLE documents ALTER text TYPE VARCHAR(255)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('DROP TABLE users');
        $this->addSql('ALTER TABLE documents ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE documents ALTER name DROP NOT NULL');
        $this->addSql('ALTER TABLE documents ALTER name TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE documents ALTER author DROP NOT NULL');
        $this->addSql('ALTER TABLE documents ALTER author TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE documents ALTER date DROP NOT NULL');
        $this->addSql('ALTER TABLE documents ALTER date TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE documents ALTER state DROP NOT NULL');
        $this->addSql('ALTER TABLE documents ALTER state TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE documents ALTER text DROP NOT NULL');
        $this->addSql('ALTER TABLE documents ALTER text TYPE VARCHAR(100)');
    }
}
